replicaCount: 2
image:
  repository: nginx
  tag: latest
  pullPolicy: IfNotPresent
ports:
- name: http
  containerPort: 80
  protocol: TCP

service:
  port: 80

ingress:
  enabled: true
  className: matas-ingress-class
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
  - hosts:
    - nginx.local.com
  hosts:
  - host: nginx.local.com
    paths:
    - path: /
      pathType: Prefix

secret:
  enabled: true
  type: kubernetes.io/tls
  data:
    tls.crt: |
      -----BEGIN CERTIFICATE-----
      MIIDpTCCAo2gAwIBAgIJAM+ZrJj7hnmlMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNV
      BAYTAkxUMRIwEAYDVQQIDAlMaXRodWFuaWExEDAOBgNVBAcMB1ZpbG5pdXMxGjAY
      BgNVBAoMEUxvY2FsIERldmVsb3BtZW50MRIwEAYDVQQDDAlsb2NhbC5jb20wHhcN
      MjQwMzIwMTA0MTE2WhcNMjUwMzIwMTA0MTE2WjBjMQswCQYDVQQGEwJMVDESMBAG
      A1UECAwJTGl0aHVhbmlhMRAwDgYDVQQHDAdWaWxuaXVzMRowGAYDVQQKDBFMb2Nh
      bCBEZXZlbG9wbWVudDESMBAGA1UEAwwJbG9jYWwuY29tMIIBIjANBgkqhkiG9w0B
      AQEFAAOCAQ8AMIIBCgKCAQEAxZbqjiYWCQFSyDugJC/8pbUSWvHLDkZN8nCWYt0F
      QF9j+ALagj/lxWktD7ZeZTr45m4R4ywN/Zr4vxfc/zpBjNNMWPh6BbonH8G7obJI
      yDwAT6KwD6AVY+NM3DbKEguRtKMKRt0PQshik5fwV0GPBRU3SxrPaH5sHtlJkyjg
      iJFh53XuLT2F/MWr0rwtBi32xLplTUmqa5fbHxMOsBwCIh/tcp9z8Lq3r6qkXGRv
      tWRTNoMb1p/9JCV3LVAOig0SCm+SWO8YG0dmQrLQzSb6L7gg7SAf1Txob/PJ5CY8
      I7O0ay4ABS8Aof/UsPb2XAnIZoDITN8fERFtfcKwSbbzqwIDAQABo1wwWjAJBgNV
      HRMEAjAAMAsGA1UdDwQEAwIE8DAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
      AwIwIQYDVR0RBBowGIIJbG9jYWwuY29tggsqLmxvY2FsLmNvbTANBgkqhkiG9w0B
      AQsFAAOCAQEATopSBg30JdExKIGhHi5MP8hhkXZOK1kFsAzREUdpy+l5cClYDGP9
      1MM9s/ia0xR4sZNoMtdMJRGBYREHDFGH9q7YrLmekPxE89WYHYqroF8LrGsHB/2T
      zvPSNYkjpvvAVZeqprTkrjuMykCF2l+Vnrc4XKpvKEV70OLwtRTzj5W/cKz/9l9u
      uhYlQQAEXJY6ri6FsT5JTnG3n6LGEkdXCrFTWuWp0VG8HpTveO23uS6ou1uwOwb1
      zatH3N9HAVobjCmdKtsiolfh8QF5WP32f/KQ64CY1LwGptPAn99R9xx/jmE1+90Q
      0GWWwSSkseCAxjRZCZQJHcKQYTu4HD+owg==
      -----END CERTIFICATE-----
    tls.key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFluqOJhYJAVLI
      O6AkL/yltRJa8csORk3ycJZi3QVAX2P4AtqCP+XFaS0Ptl5lOvjmbhHjLA39mvi/
      F9z/OkGM00xY+HoFuicfwbuhskjIPABPorAPoBVj40zcNsoSC5G0owpG3Q9CyGKT
      l/BXQY8FFTdLGs9ofmwe2UmTKOCIkWHnde4tPYX8xavSvC0GLfbEumVNSaprl9sf
      Ew6wHAIiH+1yn3PwurevqqRcZG+1ZFM2gxvWn/0kJXctUA6KDRIKb5JY7xgbR2ZC
      stDNJvovuCDtIB/VPGhv88nkJjwjs7RrLgAFLwCh/9Sw9vZcCchmgMhM3x8REW19
      wrBJtvOrAgMBAAECggEBAJhtylkK7KjZyoEJ7oq8Mk2rmJNsQNesSOmlDX8LPsfg
      TwC/Qs6EeL+IWejrKXsyuV0awNXd4JUqfob849JJoNQBFb71QT011ITdMeCV5ywB
      jcPhn60ONDIw4dRouA6fujH+LSlp1CIS8GkoJ5NI0gp7yYI5FpRoIwTRX78VI9J1
      6j/r3p+dSJGjo7/w4/fwTV2a+ronfF1l4cf4yco9mcK5DMp6CnoBjNyn5r8Y3K0a
      ZfKAROfch+xYan/3LQrR5hKrRzXGj30fKHwaTpe5NhN7uJgioLZFoQkh+mLUPne6
      VAU/2ljSwvqjhT2r5ljLsQ/Mmqjr5OWmVBEgjaoxefECgYEA6CyUQZuoR7r8iaR9
      RhbVYgj7TYYZ7rxmiVd6nXdAzSSBKdTFVF7GK2+PKBtgo8iJjM/ty2TOTT3H9j30
      XXgC8Fgq48kH66kKt6wBY5AWpsHTseBA52s7pJBNnf6w5NbPDIvw3tyOhQgK67g3
      TcuLr37oSsYKwSgyWdkRCyXlSQ0CgYEA2d3EtUpmoLTy3Bqi+jZn2yL6qxG9f4aN
      RDhq1OBj2bG+pXX6V7GSUmTYHRNVgJIM9YHDUvnG1QLFDDrOSyw7uqQswJ+SFI7s
      auIlLLL5JXBqOykMlb/6tnOWzRfyxGsy/9ZOs66+N3XADDzoWTx6mqyl78gdi5rb
      Zu4uqzZbEZcCgYEAi2uxv9A0dpav7gvr+nndu5g/KKedzQIv5Mu2Yvbo4AfK1I7j
      zK14/T5pziDaoJ/dEcUPPDOVu0adXJ6JrtNRmHipkM34xqhlOjS9RMeTAqKkeE19
      TDrVvxW0tmrqWRExlow2oe36W6KfxDuEYmAXytQ/tB9G+AUmb1Ptay9fh8UCgYAt
      W2o0hATRuFpHUJRVmzYL/UBKlSrqfcyzQzuajgy7qbGTKPixgRqBZNVJWFkYp09j
      XVyYzb+DYUw8u5FvPQpCVSOsBoyXExpNNj+fCrOsA7daEbW5B3reuTnQAQhdtCOt
      96Py7JJVYYJWCegli93Kjd8OCI9+HQNIbpXwtyRGiQKBgBsdzm1YSzqbT4EIEsoT
      PG31mR1HL3IBMEOVpy9/mVK7wKf1CE7NBWdKiXEAVpFHFrhyLNrbTI7OHWrMlxwg
      qKARR0j8d2rx2OSeCh35lHy27KBNmh+X0/FlZzN87o2e+oMQ7otUCC3hDAlbSA8V
      MvfzuFVdoxJQv4OSOWFUE4rK
      -----END PRIVATE KEY-----

ingressClass:
  enabled: true
  name: "matas-ingress-class"
  controller: k8s.io/ingress-nginx
